Create database Empresas

CREATE TABLE PERSONAS(
IDPERSONA INT IDENTITY (1,1),
NOMBRE NVARCHAR (100),
APELLIDO NVARCHAR (100),
EDAD INT,
IDOCUPACION INT,
IDVEHICULO INT,
PRIMARY KEY (IDPERSONA),
FOREIGN KEY (IDVEHICULO) REFERENCES VEHICULOS (IDVEHICULO),
FOREIGN KEY (IDOCUPACION) REFERENCES OCUPACIONES (IDOCUPACION),
)
CREATE TABLE OCUPACIONES (
IDOCUPACION INT IDENTITY (1,1),
NOMBRE_DEL_CARGO NVARCHAR (100),
ANTIGUEDAD_AÑOS INT,
PROVINCIA NVARCHAR (100),
CIUDAD NVARCHAR (100),
PRIMARY KEY (IDOCUPACION),
)

CREATE TABLE EMPRESAS (
IDEMPRESA INT IDENTITY (1,1),
NOMBRE_EMPRESA NVARCHAR (100),
NUMERO_EMPLEADOS INT,
IDOCUPACION INT,
PRIMARY KEY (IDEMPRESA),
FOREIGN KEY (IDOCUPACION) REFERENCES OCUPACIONES (IDOCUPACION),
)


CREATE TABLE VEHICULOS(
IDVEHICULO INT IDENTITY (1,1),
MARCA NVARCHAR (100),
MODELO NVARCHAR (100),
PATENTE NVARCHAR (100),
CILINDRADA_EN_CC INT,
PRIMARY KEY (IDVEHICULO),
FOREIGN KEY (IDPERSONA) REFERENCES PERSONAS (IDPERSONA),
)
