CREATE DATABASE DISPARADORES

USE DISPARADORES


CREATE TABLE PRODUCTO (
IDPRODUCTO INT IDENTITY (1,1) NOT NULL,
FECHA_OPERACION DATE,
NOMBRE_USUARIO NVARCHAR (50),
NOMBRE_PRODUCTO NVARCHAR (50),
PRECIO_PRODUCTO INT,
CANTIDAD_DISPONIBLE INT,
PRIMARY KEY (IDPRODUCTO)
)

INSERT INTO PRODUCTO (FECHA_OPERACION, NOMBRE_USUARIO,NOMBRE_PRODUCTO, PRECIO_PRODUCTO, CANTIDAD_DISPONIBLE) VALUES
('2020-02-12','ARTURO PEREZ','JUGUETES',12313,232)


CREATE TRIGGER TR_INSERT
ON PRODUCTO
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
 SELECT * FROM PRODUCTO;
END

DELETE PRODUCTO WHERE IDPRODUCTO = 10

UPDATE PRODUCTO SET NOMBRE_USUARIO = 'Bruce Banner', FECHA_OPERACION = '2020-08-05', 
NOMBRE_PRODUCTO = 'VIDEOJUEGOS', PRECIO_PRODUCTO=75464 WHERE IDPRODUCTO=9

INSERT INTO PRODUCTO (FECHA_OPERACION, NOMBRE_USUARIO,NOMBRE_PRODUCTO, PRECIO_PRODUCTO) VALUES
('2020-6-20', 'MARIANO SANCHEZ', 'COMPUTADORAS', 5364)

CREATE TABLE STOCK (
IDSTOCK INT IDENTITY (1,1) NOT NULL,
NOMBRE_PRODUCTO NVARCHAR (50),
CANTIDAD INT,
PRECIO INT,
NUMERO_SERIE INT
)


INSERT INTO STOCK (NOMBRE_PRODUCTO, CANTIDAD, PRECIO, NUMERO_SERIE) VALUES
('TARJETAS DE ACCESO', 35000, 500,420840)


CREATE TABLE COMPRA(
IDCOMPRA INT IDENTITY (1,1) NOT NULL,
CLIENTE_NOMBRE NVARCHAR (50),
DNI INT,
PRODUCTO_COMPRADO NVARCHAR (50),
CANTIDAD INT
)


CREATE TRIGGER CONTROL_STOCK
ON COMPRA
AFTER INSERT
AS
BEGIN
     DECLARE @VERIFICACION NVARCHAR (50)
	 DECLARE @DISPONIBLIDAD INT =0
	 DECLARE @DISPONIBLIDAD_ACTUALIZAR INT =0

	 SELECT @DISPONIBLIDAD=(SELECT CANTIDAD_DISPONIBLE FROM PRODUCTO WHERE IDPRODUCTO =(SELECT IDPRODUCTO FROM inserted))
	 SELECT @DISPONIBLIDAD_ACTUALIZAR=(SELECT CANTIDAD FROM inserted)

			IF (@DISPONIBLIDAD>@DISPONIBLIDAD_ACTUALIZAR)

			BEGIN TRAN 
				UPDATE PRODUCTO SET
				FECHA_OPERACION = GETDATE(),
				CANTIDAD_DISPONIBLE=@DISPONIBLIDAD-@DISPONIBLIDAD_ACTUALIZAR
				WHERE IDPRODUCTO=(SELECT IDPRODUCTO FROM inserted)
				COMMIT TRAN
			END
			ELSE
	BEGIN
	SET @VERIFICACION= 'FALTO DE STOCK, OPERACION NO EJECUTABLE' + (SELECT NOMBRE_PRODUCTO FROM PRODUCTO 
	INNER JOIN inserted ON PRODUCTO.IDPRODUCTO=inserted.IDCOMPRA) + '.' PRINT @VERIFICACION ROLLBACK TRAN
	END

	END